name: Build PyOxidizer Binary

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

env:
  VERSION: 3.19

jobs:
  

  build-linux-musl:
    name: Build Linux (musl)
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64
    env:
      musl_version: 1.2.4

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          echo "PATH=$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pyoxidizer/
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: linux-musl-cache

      - name: Setup musl
        run: |
          curl -L https://www.musl-libc.org/releases/musl-${{ env.musl_version }}.tar.gz | tar -xzf -
          cd musl-*
          ./configure --exec-prefix=/usr/local
          make
          make install

      - name: Install forked PyOxidizer
        run: cargo install --git https://github.com/fox-it/pyoxidizer --branch esxi-compatibility pyoxidizer --force --locked

      - name: Install dependencies
        run: /opt/python/cp39-cp39/bin/pip install dissect

      - name: Build binary
        run: |
          mkdir -p build/lib/dissect/target/plugins
          /opt/python/cp39-cp39/bin/target-build-pluginlist > build/lib/dissect/target/plugins/_pluginlist.py
          pyoxidizer build --release --target-triple x86_64-unknown-linux-musl --var flavor standalone --var version ${{ env.VERSION }}
          strip build/x86_64-unknown-linux-musl/release/install/acquire

      - name: Verify binary
        run: build/x86_64-unknown-linux-musl/release/install/target-shell --help

      - uses: actions/upload-artifact@v4
        with:
          name: acquire-linux-musl
          path: build/x86_64-unknown-linux-musl/release/install/*
